services:
  db:
    image: postgres:16.2-alpine
    container_name: monodb
    restart: always
    hostname: localhost
    environment:
      - POSTGRES_DB=monodb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: local@temp.com
      PGADMIN_DEFAULT_PASSWORD: pass123
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin-data: