services:
  db:
    image: postgres:16.2-alpine
    container_name: monodb
    restart: always
    hostname: localhost
    environment:
      - POSTGRES_DB=monodb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: local@temp.com
      PGADMIN_DEFAULT_PASSWORD: pass123
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  keycloak_db:
    image: postgres:16.2-alpine
    container_name: keycloak_db
    volumes:
      - keycloak-data:/var/lib/postgresql/keycloakdata
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak_web:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloak_db
    ports:
      - 8080:8080

volumes:
  postgres:
  pgadmin-data:
  keycloak-data:
