export enum sortByEnum {
  LowHigh = "LowHigh",
  HighLow = "HighLow",
}

export enum CategoriesEnum {
  "case-accessory"= "case-accessory",
  "case-fan"= "case-fan",
  "case"= "case",
  "cpu-cooler"= "cpu-cooler",
  "cpu"= "cpu",
  "external-hard-drive"= "external-hard-drive",
  "fan-controller"= "fan-controller",
  "headphones"= "headphones",
  "internal-hard-drive"= "internal-hard-drive",
  "keyboard"= "keyboard",
  "memory"= "memory",
  "monitor"= "monitor",
  "motherboard"= "motherboard",
  "mouse"= "mouse",
  "optical-drive"= "optical-drive",
  "os"= "os",
  "power-supply"= "power-supply",
  "sound-card"= "sound-card",
  "speakers"= "speakers",
  "thermal-paste"= "thermal-paste",
  "ups"= "ups",
  "video-card"= "video-card",
  "webcam"= "webcam",
  "wired-network-card"= "wired-network-card",
  "wireless-network-card"= "wireless-network-card",
}