name: PartsShop Backend / Build Image & Push

on:
  push:
    branches:
      - prod


jobs:
  build:
    name: Build / Artifact
    runs-on: ubuntu-latest
    environment: Actions
    env:
      BUILD_NUMBER: ${{ github.run_number }}

    strategy:
      matrix:
        node-version: [20]

    permissions:
        id-token: write
        contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

                    

    #   - name: "Configure AWS Credentials"
    #     uses: aws-actions/configure-aws-credentials@v4.0.2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::008971640623:role/dockerBuilder



      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1
      
      - name: Create Docker Image
        run: |
          rm -rf node_modules .dist
          yarn cache clean
          version=$(npx -c 'echo $npm_package_version')
          docker build . -t partsshop:$version
      
      - name: Tag and Push
        env:
            ecr_repository_uri: ${{ secrets.ECR_REPOSITORY_URI }}
        run: |
          version=$(npx -c 'echo $npm_package_version')
          docker tag partsshop:$version ${{ env.ecr_repository_uri }}:$version-${{ env.BUILD_NUMBER }}
          docker tag partsshop:$version ${{ env.ecr_repository_uri }}:latest
          docker push ${{ env.ecr_repository_uri }}:$version-${{ env.BUILD_NUMBER }}
          docker push ${{ env.ecr_repository_uri }}:latest